# Generated by Django 4.2.2 on 2023-06-13 21:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0004_emailverificationtoken'),
    ]

    operations = [
        migrations.AlterModelManagers(
            name='user',
            managers=[
            ],
        ),
    ]
