# Generated by Django 4.2.2 on 2023-06-16 03:46

import apps.accounts.utils
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0006_alter_user_is_active'),
    ]

    operations = [
        migrations.AlterField(
            model_name='emailverificationtoken',
            name='expired_at',
            field=models.DateTimeField(default=apps.accounts.utils.get_expiration_date),
        ),
    ]
