version: "3"

services:
  task-manager:
    container_name: task-manager-local
    build:
      context: .
      dockerfile: ./compose/local/dockerfiles/Dockerfile-task-manager
      args:
        REQUIREMENTS_FILE: local.txt
    env_file: .env
    command: sh -c "python manage.py migrate && python manage.py runserver 0.0.0.0:8000"
    volumes:
      - .:/app
      - ./volumes/tmp/app-messages:/tmp/app-messages
      - ./volumes/var/logs:/var/logs
    ports:
      - "8000:8000"
    working_dir: /app
    environment:
      - DJANGO_ENV=local
      - DJANGO_SETTINGS_MODULE=task_manager.settings.local
      - DEBUG=True
      - POSTGRES_HOST=task-manager-db
      - POSTGRES_PORT=5432
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_DB=task_manager_db
    stdin_open: true
    tty: true
    restart: always
    depends_on:
      - task-manager-db
      - task-manager-worker
      - redis

  task-manager-db:
    image: postgres:15-alpine
    container_name: task-manager-db-local
    ports:
      - 5432:5432
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_DB=task_manager_db
    volumes:
      - ./volumes/task-manager-db:/var/lib/postgresql/data
      - ./init-db/postgres:/docker-entrypoint-initdb.d/

  task-manager-worker:
    platform: linux/amd64
    container_name: task-manager-worker-local
    build:
      context: .
      dockerfile: ./compose/local/dockerfiles/Dockerfile-task-manager
      args:
        REQUIREMENTS_FILE: local.txt
    env_file: .env
    command: celery -A task_manager worker -l info
    volumes:
      - .:/app
      - ./volumes/tmp/app-messages:/tmp/app-messages
      - ./volumes/var/logs:/var/logs
    ports:
      - "8001:8000"
    working_dir: /app
    environment:
      - DJANGO_ENV=local
      - DJANGO_SETTINGS_MODULE=task_manager.settings.local
      - DEBUG=True
      - POSTGRES_HOST=task-manager-db
      - POSTGRES_PORT=5432
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_DB=task_manager_db
      - REDIS_HOST=redis
      - REDIS_PORT=6379
      - REDIS_CACHE_URL=redis://redis:6379/1
      - CELERY_BROKER_URL=redis://redis:6379/2
    depends_on:
      - task-manager-db
      - redis
    stdin_open: true
    tty: true
    restart: always

  redis:
    image: redis:latest
    container_name: redis-local
    ports:
      - 6379:6379
    restart: always

  flower:
    platform: linux/amd64
    image: mher/flower
    environment:
      - CELERY_BROKER_URL=redis://redis:6379/2
      - FLOWER_PORT=8888
    ports:
      - 8888:8888
    depends_on:
      - task-manager-worker
