# Generated by Django 4.2.2 on 2023-06-16 03:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('assignments', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='assignments',
            options={'verbose_name': 'Assignment', 'verbose_name_plural': 'Assignments'},
        ),
    ]
