name: Django CI

on:
  push:
    branches: [ "dev" ]
jobs:
  tests:

    runs-on: ubuntu-latest
    strategy:
      max-parallel: 4
      matrix:
        python-version: [3.8,]

    steps:
    - uses: actions/checkout@v3
    - name: Set up Python ${{ matrix.python-version }}
      uses: actions/setup-python@v3
      with:
        python-version: ${{ matrix.python-version }}
    - name: Install Dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements/test.txt
    - name: Run Tests
      env:
        ALLOWED_HOSTS: ${{ secrets.ALLOWED_HOSTS }}
        DJANGO_ENV: ${{ secrets.DJANGO_ENV }}
        DJANGO_SETTINGS_MODULE: ${{ secrets.DJANGO_SETTINGS_MODULE }}
        DEBUG: ${{ secrets.DEBUG }}
        EMAIL_BACKEND: ${{ secrets.EMAIL_BACKEND }}
        EMAIL_HOST: ${{ secrets.EMAIL_HOST }}
        EMAIL_HOST_USER: ${{ secrets.EMAIL_HOST_USER }}
        EMAIL_HOST_PASSWORD: ${{ secrets.EMAIL_HOST_PASSWORD }}
        EMAIL_PORT: ${{ secrets.EMAIL_PORT }}
        JWT_SIGNING_KEY: ${{ secrets.JWT_SIGNING_KEY }}
        REGISTRATION_EMAIL_CONFIRM_ENABLED: ${{ secrets.REGISTRATION_EMAIL_CONFIRM_ENABLED }}
        REGISTRATION_EMAIL_BASE_URL: ${{ secrets.REGISTRATION_EMAIL_BASE_URL }}
        REGISTRATION_EMAIL_FROM: ${{ secrets.REGISTRATION_EMAIL_FROM }}
        SECRET_KEY: ${{ secrets.SECRET_KEY }}
      run: |
        pytest --cov=apps --cov-report html
        coverage report
